[package]
name = "rusty-bucket"
version = "0.1.0"
authors = ["shaileshv", "hab278"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-s3 = "0.22.12"
aws-creds = "0.23.1"
